spring.datasource.url=jdbc:mysql://localhost:3306/panna_diamond
spring.datasource.username=root
spring.datasource.password=Shivasati@1136

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true